project_id = "lpqatjynvfyhrizaioxi"

[functions.fleet-monitoring]
verify_jwt = false

[functions.check-printer-status]
verify_jwt = false

[functions.license]
verify_jwt = false

[functions.trigger-build]
verify_jwt = false

[functions.github-build-status]
verify_jwt = false

[functions.verify-dev-access]
verify_jwt = false

[functions.generate-license]
verify_jwt = false

[functions.feedback-admin]
verify_jwt = false

[functions.receive-print-data]
verify_jwt = false

[functions.serve-asset]
verify_jwt = false